# Generated by Django 5.0.6 on 2024-05-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tender_id', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('num_tenders_done', models.IntegerField(default=0)),
                ('license_id', models.CharField(max_length=100)),
                ('license_photo', models.ImageField(upload_to='license_photos/')),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
